In [1]:
print("Hello World")

Hello World

In [3]:
# EDA.ipynb — Cell 1
from pathlib import Path
import pandas as pd

# Point to your project root (the folder that contains 'data')
# If EDA.ipynb is already in that folder, Path.cwd() is fine.
ROOT = Path.cwd()

DATA_DIR = ROOT / "data"

# File names (exactly as shown in Explorer)
books_csv = DATA_DIR / "03_Library Systembook.csv"
customers_csv = DATA_DIR / "03_Library SystemCustomers.csv"

books_csv, customers_csv

(WindowsPath('c:/Users/Admin/Documents/GitHub/DE5-M5/data/03_Library Systembook.csv'),
 WindowsPath('c:/Users/Admin/Documents/GitHub/DE5-M5/data/03_Library SystemCustomers.csv'))

In [5]:

books_df = pd.read_csv(books_csv)
cust_df  = pd.read_csv(customers_csv)

print("Books shape:", books_df.shape)
print("Customers shape:", cust_df.shape)

books_df.head(2), cust_df.head(2)

Books shape: (114, 6)
Customers shape: (9, 2)

(    Id                             Books Book checkout Book Returned  \
 0  1.0               Catcher in the Rye   "20/02/2023"    25/02/2023
 1  2.0  Lord of the rings the two towers  "24/03/2023"    21/03/2023

   Days allowed to borrow  Customer ID
 0                2 weeks          1.0
 1                2 weeks          2.0  ,
    Customer ID Customer Name
 0          1.0      Jane Doe
 1          2.0    John Smith)

In [8]:
cust_df.head()

   Customer ID   Customer Name
0          1.0        Jane Doe
1          2.0      John Smith
2          3.0      Dan Reeves
3          NaN             NaN
4          5.0  William Holden

In [10]:
books_df.info()
cust_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      21 non-null     float64
 1   Books                   20 non-null     object
 2   Book checkout           21 non-null     object
 3   Book Returned           21 non-null     object
 4   Days allowed to borrow  21 non-null     object
 5   Customer ID             20 non-null     float64
dtypes: float64(2), object(4)
memory usage: 5.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    8 non-null      float64
 1   Customer Name  8 non-null      object
dtypes: float64(1), object(1)
memory usage: 276.0+ bytes

In [11]:
def quick_check(df):
    print("Shape (rows, columns):", df.shape)
    print("\nColumn types:")
    print(df.dtypes)

    print("\nMissing values per column:")
    print(df.isna().sum())

    print("\nFirst 3 rows:")
    print(df.head(3))

In [12]:
quick_check(books_df)
quick_check(cust_df)

Shape (rows, columns): (114, 6)

Column types:
Id                        float64
Books                      object
Book checkout              object
Book Returned              object
Days allowed to borrow     object
Customer ID               float64
dtype: object

Missing values per column:
Id                        93
Books                     94
Book checkout             93
Book Returned             93
Days allowed to borrow    93
Customer ID               94
dtype: int64

First 3 rows:
    Id                                     Books Book checkout Book Returned  \
0  1.0                       Catcher in the Rye   "20/02/2023"    25/02/2023
1  2.0          Lord of the rings the two towers  "24/03/2023"    21/03/2023
2  3.0  Lord of the rings the return of the kind  "29/03/2023"    25/03/2023

  Days allowed to borrow  Customer ID
0                2 weeks          1.0
1                2 weeks          2.0
2                2 weeks          3.0
Shape (rows, columns): (9, 2)

Column types:
Customer ID      float64
Customer Name     object
dtype: object

Missing values per column:
Customer ID      1
Customer Name    1
dtype: int64

First 3 rows:
   Customer ID Customer Name
0          1.0      Jane Doe
1          2.0    John Smith
2          3.0    Dan Reeves

In [16]:
quick_check(cust_df)

Shape (rows, columns): (9, 2)

Column types:
Customer ID      float64
Customer Name     object
dtype: object

Missing values per column:
Customer ID      1
Customer Name    1
dtype: int64

First 3 rows:
   Customer ID Customer Name
0          1.0      Jane Doe
1          2.0    John Smith
2          3.0    Dan Reeves

In [13]:
print("Columns:", books_df.columns.tolist())
print("Shape:", books_df.shape)
books_df.head(10)

Columns: ['Id', 'Books', 'Book checkout', 'Book Returned', 'Days allowed to borrow', 'Customer ID']
Shape: (114, 6)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0
5,6.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
6,7.0,IT,"""10/04/2063""",03/04/2023,2 weeks,6.0
7,8.0,Misery,"""15/04/2023""",03/04/2023,2 weeks,7.0
8,9.0,Catch 22,"""15/04/2023""",16/04/2023,2 weeks,7.0
9,10.0,Animal Farm,"""20/04/2023""",24/04/2023,2 weeks,2.0

In [15]:
books_missing_rows = books_df[books_df.isna().any(axis=1)]
books_missing_rows

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
20,21.0,NaN,"""01/06/2023""",05/06/2023,2 weeks,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
109,NaN,NaN,NaN,NaN,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN
111,NaN,NaN,NaN,NaN,NaN,NaN
112,NaN,NaN,NaN,NaN,NaN,NaN
113,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
books_df_v0_01 = books_df.dropna()
cust_df_v0_01 = cust_df.dropna()

In [19]:
missing_table = cust_df_v0_01.isna().sum().reset_index()
missing_table.columns = ["column", "missing_count"]
missing_table

          column  missing_count
0    Customer ID              0
1  Customer Name              0

In [20]:
missing_table = books_df_v0_01.isna().sum().reset_index()
missing_table.columns = ["column", "missing_count"]
missing_table

                   column  missing_count
0                      Id              0
1                   Books              0
2           Book checkout              0
3           Book Returned              0
4  Days allowed to borrow              0
5             Customer ID              0

In [30]:
books_df_v01 = books_df.dropna()
books_df_v01.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0

In [31]:

books_df_v01["Book checkout"] = (
    books_df_v01["Book checkout"]
    .astype(str)
    .str.replace('"', '', regex=False)   # remove quotes
    .str.strip()                          # remove spaces
    .pipe(pd.to_datetime, errors="coerce", dayfirst=True)
)

# Clean Book Returned
books_df_v01["Book Returned"] = (
    books_df_v01["Book Returned"]
    .astype(str)
    .str.replace('"', '', regex=False)
    .str.strip()
    .pipe(pd.to_datetime, errors="coerce", dayfirst=True)
)

C:\Users\Admin\AppData\Local\Temp\ipykernel_13568\3638101849.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books_df_v01["Book checkout"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_13568\3638101849.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books_df_v01["Book Returned"] = (

In [32]:
# Clean Book checkout
books_df_v01.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,2 weeks,1.0
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,2 weeks,3.0
3,4.0,The hobbit,2023-04-02,2023-03-25,2 weeks,4.0
4,5.0,Dune,2023-04-02,2023-03-25,2 weeks,5.0

In [35]:
# Convert "X weeks" → X*7 days
books_df_v01["Days allowed to borrow"] = (
    books_df_v01["Days allowed to borrow"]
        .str.split()
        .str[0]        # extract the number
        .astype(int)   # convert to int
        .mul(7)        # multiply by 7 days
)
books_df_v01.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_13568\1034890117.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books_df_v01["Days allowed to borrow"] = (

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,14,1.0
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,14,2.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,14,3.0
3,4.0,The hobbit,2023-04-02,2023-03-25,14,4.0
4,5.0,Dune,2023-04-02,2023-03-25,14,5.0

In [34]:
cust_df_v01 = cust_df.dropna()
cust_df_v01.head()

   Customer ID   Customer Name
0          1.0        Jane Doe
1          2.0      John Smith
2          3.0      Dan Reeves
4          5.0  William Holden
5          6.0   Jaztyn Forest

In [36]:
books_df_v01.dtypes

Id                               float64
Books                             object
Book checkout             datetime64[ns]
Book Returned             datetime64[ns]
Days allowed to borrow             int32
Customer ID                      float64
dtype: object